// <auto-generated />
using Gyms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Gyms.Migrations
{
    [DbContext(typeof(GymsContext))]
    [Migration("20171013144353_ClassDuration")]
    partial class ClassDuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gyms.Models.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("InstructorID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("InstructorID");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("Gyms.Models.ClassAttendance", b =>
                {
                    b.Property<int>("ClassId");

                    b.Property<int>("ClientId");

                    b.HasKey("ClassId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClassAttendance");
                });

            modelBuilder.Entity("Gyms.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Gyms.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("Gyms.Models.Class", b =>
                {
                    b.HasOne("Gyms.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gyms.Models.ClassAttendance", b =>
                {
                    b.HasOne("Gyms.Models.Class", "Class")
                        .WithMany("ClassAttendance")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gyms.Models.Client", "Client")
                        .WithMany("ClassAttendance")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
